// Generates migrations/0002_seed.sql from the existing JSON data files so the
// D1 database is seeded with the same products and categories the app shipped with.
// Run with: npm run db:generate-seed

import { readFileSync, writeFileSync, readdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, "..");
const productsDir = join(root, "src", "data", "products");
const categoriesFile = join(root, "src", "data", "categories.json");
const outFile = join(root, "migrations", "0002_seed.sql");

/** Escape a value for a single-quoted SQL string literal. */
function sqlString(value) {
  if (value === undefined || value === null) return "NULL";
  return `'${String(value).replace(/'/g, "''")}'`;
}

/** Serialize an object/array to a JSON SQL string literal. */
function sqlJson(value, fallback = "[]") {
  if (value === undefined || value === null) return sqlString(fallback);
  return sqlString(JSON.stringify(value));
}

const productFiles = readdirSync(productsDir)
  .filter((f) => f.endsWith(".json"))
  .sort();

// Preserve the display order defined in index.ts.
const orderSource = readFileSync(join(productsDir, "index.ts"), "utf8");
const orderMatch = orderSource.match(/export const products[^=]*=\s*\[([\s\S]*?)\]/);
const orderNames = orderMatch
  ? orderMatch[1]
      .split(",")
      .map((s) => s.trim())
      .filter(Boolean)
  : [];

// Map camelCase import names -> file basenames so we can order by index.ts.
const importMap = {};
for (const line of orderSource.split("\n")) {
  const m = line.match(/import\s+(\w+)\s+from\s+"\.\/([\w-]+)\.json"/);
  if (m) importMap[m[1]] = `${m[2]}.json`;
}

const orderedFiles = orderNames
  .map((name) => importMap[name])
  .filter((f) => f && productFiles.includes(f));
// Append any product files not referenced in index.ts, just in case.
for (const f of productFiles) if (!orderedFiles.includes(f)) orderedFiles.push(f);

const lines = [];
lines.push("-- 0002_seed.sql");
lines.push("-- Auto-generated by scripts/generate-seed.mjs. Do not edit by hand.");
lines.push("-- Re-run `npm run db:generate-seed` after changing JSON seed data.");
lines.push("");

let sortOrder = 0;
for (const file of orderedFiles) {
  const p = JSON.parse(readFileSync(join(productsDir, file), "utf8"));
  const cols = [
    "id",
    "slug",
    "name",
    "brand",
    "category",
    "subcategory",
    "short_description",
    "description",
    "material",
    "comfort",
    "firmness",
    "thickness",
    "warranty",
    "images",
    "features",
    "specifications",
    "sizes",
    "tags",
    "faqs",
    "feature_tiles",
    "commercial",
    "testimonials",
    "sort_order"
  ];
  const values = [
    sqlString(p.id),
    sqlString(p.slug),
    sqlString(p.name),
    sqlString(p.brand),
    sqlString(p.category),
    sqlString(p.subcategory),
    sqlString(p.shortDescription ?? null),
    sqlString(p.description),
    sqlString(p.material ?? null),
    sqlString(p.comfort ?? null),
    sqlString(p.firmness ?? null),
    sqlString(p.thickness),
    sqlString(p.warranty),
    sqlJson(p.images, "[]"),
    sqlJson(p.features, "[]"),
    sqlJson(p.specifications, "[]"),
    sqlJson(p.sizes, "[]"),
    sqlJson(p.tags, "[]"),
    sqlJson(p.faqs, "[]"),
    p.featureTiles ? sqlJson(p.featureTiles, "{}") : "NULL",
    p.commercial ? sqlJson(p.commercial, "{}") : "NULL",
    sqlJson(p.testimonials, "[]"),
    String(sortOrder)
  ];
  lines.push(`INSERT OR REPLACE INTO products (${cols.join(", ")}) VALUES`);
  lines.push(`  (${values.join(", ")});`);
  lines.push("");
  sortOrder += 1;
}

const categories = JSON.parse(readFileSync(categoriesFile, "utf8"));
let catOrder = 0;
for (const c of categories) {
  const cols = ["id", "name", "slug", "description", "image", "product_count", "sort_order"];
  const values = [
    sqlString(c.id),
    sqlString(c.name),
    sqlString(c.slug),
    sqlString(c.description),
    sqlString(c.image),
    String(c.productCount ?? 0),
    String(catOrder)
  ];
  lines.push(`INSERT OR REPLACE INTO categories (${cols.join(", ")}) VALUES`);
  lines.push(`  (${values.join(", ")});`);
  lines.push("");
  catOrder += 1;
}

writeFileSync(outFile, lines.join("\n"));
console.log(
  `Wrote ${outFile} (${orderedFiles.length} products, ${categories.length} categories)`
);
